### ISSUE TITLE
Temporary fix to calculate tas indices for BARPA

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#14]
Hi Damien,

Sorry I don't know how to create a pull request in git. Could you please modify L220 in run_icclim.py to: 
`elif variable in ['tas', 't2m', '2t', 'tasmean']:`
Including tasmean will support BARPA runs which have currently named tas as tasmean.

Thanks!

**Comment by DamienIrving** [comment]
Done :smile: https://github.com/AusClimateService/indices/commit/c12ea23ffb4132c138c77583abbac510f5b04a2e
