### ISSUE TITLE
Add support for save_thresholds parameter

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#18]
Hi Damien, if it's not too much trouble can you add support for the `save_thresholds` parameter? 

This option saves the threshold values to the output netCDF file when calculating percentiles. It will be useful to compare historical/future thresholds and also for calculating future percentiles relative to the historical threshold. Thanks!

**Comment by DamienIrving** [comment]
No problem - I've updated the script so that `save_thresholds = True` always. https://github.com/AusClimateService/indices/commit/a8f834d72377bab2ecde6dcee487aca753e57c78

**Comment by ngben** [comment]
Thanks Damien, there was an issue with non-percentile indices so I've created a pull request to fix it.
