### ISSUE TITLE
Output temperature units

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#23]
I think the current version outputs temperature indices with units "C" whereas previously it was "°C".
For some reason this is breaking things in ILAMB. Is it possible to keep the units as "°C"? What is the standard meant to be?

```
  File "/home/599/bxn599/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 919, in convert
    src_unit.convert(self.data,tar_unit,inplace=True)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/cf_units/__init__.py", line 1918, in convert
    raise ValueError(
ValueError: Unable to convert from 'Unit('C')' to 'Unit('°C')'.
```

**Comment by hot007** [comment]
Hi @ngben , CF standard units I believe are `K`, you can use `degrees C` or similar, but I think use of the ° symbol is not preferred because not all parsers support non-ascii characters. It ought to be okay, but probably better to use the word 'degrees' instead - however, given the error you're having here, probably worth checking that that does in fact work, seeing it seems to be wanting to produce specifically the degrees symbol. See e.g. the comment at the top of this table re UDUNITS conversions for air temperature. http://cfconventions.org/Data/cf-standard-names/41/build/cf-standard-name-table.html

**Comment by ngben** [comment]
Thanks Claire, after playing around a bit it seems as if cf_units doesn't convert from `C` to `K` or vice versa. Celsius units have to be `degC` for cf_units to convert the units to `K`. I think ILAMB is using cf_units to convert and standardise the units from input files.

Using conda/analysis3-22.10:
```$ python
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29)
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cf_units import Unit
>>> degC=Unit("degC")
>>> C=Unit("C")
>>> K=Unit("K")
>>> degK=Unit("degK")
>>> degK.convert(273.15,degC)
0.0
>>> degK.convert(273.15,C)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/cf_units/__init__.py", line 1918, in convert
    raise ValueError(
ValueError: Unable to convert from 'Unit('degK')' to 'Unit('C')'.
>>> C.convert(0,K)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-22.10/lib/python3.9/site-packages/cf_units/__init__.py", line 1918, in convert
    raise ValueError(
ValueError: Unable to convert from 'Unit('C')' to 'Unit('K')'.
>>> degC.convert(0,K)
273.15
>>>
```

Perhaps it might be better for Line 108 in `utils_fileio.py` to be `degC`?

**Comment by DamienIrving** [comment]
Changing line 108 of `utils_fileio.py` to `index_ds[index_name].attrs['units'] = 'degC'` sounds good to me.

How's that? https://github.com/AusClimateService/indices/commit/ec8764e83cd0bc71ee05480461cc3462aaea54b7

**Comment by ngben** [comment]
Great, thank you Damien!
